name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }}-Python${{ matrix.py }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os:
        - Ubuntu
        - Windows
        - MacOS
        py:
        - 3.5
        - 3.6
        - 3.7
        - 3.8

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.py }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.py }}

    # Get the latest tox
    - name: Install tox
      run: python -m pip install tox

    # Main check
    - name: Run test suite for ${{ matrix.os }}-Python${{ matrix.py }}
      run: python -m tox -e py
